{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-admin-credentials",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-admin-credentials",
        "namespace": "monitoring"
      }
    },
    "encryptedData": {
      "admin-password": "AgBM98qXqtZGVfVVhRN8J6GvX4LB/zTIIvTfAI84YxCXKkyOgQQ+WWIC2pJEz+afke2HuivjoWUTem1zB9lMIdYIuUTVZ2VzAUqEGMgxu+qw8rePyHLNtj5Pvz0TYV8YQYqQwdIo1zdMHO6jpSb1Ih7Hdtso/Q2pct+z7GAqKS77uEAv/7Lu3QIFK0P0LKDNioKtm+jqAKW64l/m6PzxuaDX70Fl7y8R9sE/CeeTFBrXsNlvqhzGDb3vl4mG/qEpZY25VymSsyHhRRqoGoOjohNF2hqrpKj8072kHPf/nhzVVXu5HryII7r7VEqDJnFXYU3adZIxdGAQpBWmC8ODJeoJLdzJxyC/tUFpDD47YWWkccoOrwCnhZcAw1ENrITIbzqq3ixVKX7qEvzwEUcwz+zAtPxpScPtIjGz03HIGcVrIjp7iVdM8Doa6Xy17VEEt1o7Rd2wmGzzz3A3xZhaOikEMU/5UNihcPd082PhPCT8i7FJzwamRC7yTSjhh07TjMI6CHfByI36I38BTt6tvzsug274XPhUdp2VSvbk/N2oZkFV3C4zxUKxwB2KUICqRGYvrao53oLLDbIXZpgWpIb36JFW69mzfXTvy2iDNJJLcScPH9DrrHFUSO0cIYDCZ39tX6kh0neMYBOyQ7TMGzUtto/OVvY03b8Fhe05LSLZV+9pigboPzlhCCDV2M+o/JMxaAFDEdpzSH1/qTuR8akoD4Y="
    }
  }
}
