{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "minio-root-credentials",
    "namespace": "minio"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "minio-root-credentials",
        "namespace": "minio"
      }
    },
    "encryptedData": {
      "root-password": "AgCAtNy9shiF0ITwgvCpPcU4mLmuSpZIjJoZwIGyrXFiUwN/o1Qns7VzErJKAK7v03BeBiud81KyLt4MEuDee/sdFp78QIaWVbuNi/Es8+Th/OZwecwkPHm1JvUWwzTfNQfrCXH99HECKhN+Mlrt3NNBSDUAwt7xv5VplGh/IDqidPvf47WuSRK+0RNs2mT5lxM/WasNjr0MsrwXWCDvj9HlizZ8ZqT1gmK/ZREeqWVJXfbce74fY3AYSemLgJy73U2yTyqL3hysUHfMfGNXgDMMX0gUEHeqNb5Znl6j0SQFY13nFnaQgFPy0kLBB3CH/gxchftojR7c5n4eMWQDeaRAwD4CpdaGLH+x2DTKDL5ipgWa/qF5LoXarmLUvRWsZ2P7l9leWH8+UJnq7gMJcO3IKN2Ap55wN4BlL0LAFVBGrBlRxNsU4cW+/ohDivFs3rApWM2gWHHLxGWBXU1Ka3LfUMGqCNfYxfHWMbLlhitYvqX48Fr/kv9OnAKouD7j7W/ns/taWut+VrTkermukJHOrHL0r+xzNmP0/4jwo/1M36JXD9EePApJMTRDA7xNkcYMS35Q0wCCUcuOq+1QBfacvXpvSy5ed0pk7zj31hr11/qIJ0p1VOXjL6FTyk2ToSzYBQa1t3DdxEI7O+wgMuP65gSUMzEkAyy8v6WThuHSrx/IVqa1b0/KLMsbe79sAYnIMklJBIA1nm0IYNGmEwwOuls=",
      "root-user": "AgBls60kG6veY29X0jkzrsSG14u/atssXtNosdci9sUP9RqQgRWh2OjH+KZTqDWpGVplQMObUntrpHvXDlg7b8Mt+nrT3X+GOLv2Bo1yld8LFtCRbCfgKcS3NfSorKnHdAYYPcbLR3PraJ0+dUDl+bHV4Pg53p6c7MKvts07GrwMZDNr29pmGSUhg/BaoxF6sQ+ZwGMVdZaX5cCf+IdJ3WzNJREZJIVF2RJsBij60UyAyTssC41wCI8uADkRl7+0um0Q8uvBOnHsHbr3txPxSjkT3SJMA5ZO4z8woSYRf1+1Pwh/jM4HjKJESA6Sc7lUnW+cYu1jVCG88/QN5830L/URbYXA5eGiZZbA45N5RwdcL/tOiN3C1wNojmDrPSM+Z53Qayp7XZ+QqdktjjxuI7AZxfUvqgO5VLM/NuCE+FOMAQ10qK5K9Q2Zdgmf6BK0zvXCnt07DUPWCVi4kexqIN0xm0ikilGeotuRPjSZDF2chD8a3qy9/HQMxlHNLm0Ru51K1Cxz6JDd47o/jxUQ2ALP+hGm6/OwXNvE1snPWBWbo0cX63N5Ukb1SJwPuxbfIYZ84BC5h0G+cx9YU/5B/xNZejbQWZaEuoi83zhDXPmKJIDvEfV4hNHyrVx1FeYMgOeqe49Y412W+YZqFnkHzJcIwGGN2XR2ZLNkMRQUHzTP+/s/XC5KKTdU7/l3MIeUHEmLyYLOsL84jJJh"
    }
  }
}
