$ANSIBLE_VAULT;1.1;AES256
34353732653363306231366539613166666530663736363562633538366364346139663365376539
3831626236313863613764326463313235323737363331650a336162666531346564616536366661
37303534386363363865616539353261356461386532306439333437656562313231376231343032
6366613466666162370a383334646662343230333865613066383164613934393932353061643064
66356333656536306531386633636131613764356362306361313963333936613665616261623962
38306232363066303761656434356434333361376338663637313336653638633062343234326136
31373432643332346230383534616165333765353661646464626530653537333266363733646363
32663138373630613061356339386139633238363263643163376465303831333631633861356130
39343633303863636138333730353030633165346236363164613562646433316462343539613162
38633461653637383163653966616562313431373933333036353439636336393636316336333566
63633262343261396432663231636337613539336164653865333635333630393338626230393538
37363139303866613937383539646432363937303963373933393066386435666433366537333231
35323766303462323636396232383265303939363435623965343162323563643363623832393334
36363866666532343533613362306533393963393863393664643730653431353165643939663863
39303636303761393039396633343834313234383965393731346334363561376365363162653462
64373930626162613166
