$ANSIBLE_VAULT;1.1;AES256
31383463653034376639656361383563313230626665303164373937373739643531303537393336
3162633133366536313336613563326361333135666632380a316136353738316165376439363337
62633234633432316134303132643732343536646433323339656638623665633932636663393235
3362666663363866370a656530353563313862353165316365396631303230643935663937316533
39363264616335333433323538636637353066373737346535626537393134353164356564623537
66366666303537353432626161323731313833613731333137313231643165356232653337323361
38353665313331613236373832336339666435393433653531343435316162353462613664323938
61376536396161393132376630633263373132623234366464386566613838363663343435303538
33663630383339323661313535626634333965363139333764343038373437633235653330643439
37343832346464653531323361383637623630316333376638623835316534663338666335316665
62303538373439623663313134633135653962343133613566363763656535333065323832626538
64306461346536386438373231623965386639353565316430393638336534356639653530643363
66316235383662666230313137306134613865336136326665316365303465343364616633363338
31353866653639333030633732393139623261333431666161353936383263623938386134353731
37333666653435303362386463336434363239333031663331313465333266373136326439363466
34323063383664363866303965373633626133356234383231356538646334303937326263383230
62373164626430333661396238373734663566373737366533383332666361343063623038613065
66343534343131663836306437636166336134656431323738663733386532373733386637653239
34363062663265626663383564636235316361316664383230623237636439383637363839303364
62323966623739373739
