$ANSIBLE_VAULT;1.1;AES256
63393264386137353830336264363930356165306336616333323034343430323339356435343462
3533343863333238643739306530363265356531643037380a363864356537626433313765323865
31303030383033613862303239636262313034616565383030323139626333303331663731383238
3938663239303734640a333930303065306432663864666165373162333864663737336266353036
30343334313631666463363534646536646533346163656265373836386464353863646564316539
63353030653264633161333537643564633763366262356438306465616135353734333031643537
62646538393765363361333339663261303862366230333034636130646130326663393630363463
33373938653238343763346235356363316332376436373539303637366230663335333533313466
35303438303665383639643138653734643037326436333030656436343434363863343632613331
30663334633638656437653035366261353630323062313139323933663963396633643735303932
36303361663861363634343334356132333565626435363538373933626334623434323032616666
65626235636439643337623564613862326630326531353765343863323561626536663637626534
34643435356331393938653661653534616133373036386666653734663333336330636465306234
65363936396634303434666637626362663935306132356362366331393661313735356262363838
38396466386663666464633739643932363230663537653737333436363338393937306439303539
33613533393666323838
