---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik/application.yaml
  - longhorn/application.yaml
  - minio/application.yaml
  - grafana/application.yaml
  - pihole/application.yaml
